"""Prospective acceptance mapping: every gate names executed evidence."""
GATE_TESTS = {
    "artifact_tamper": ["TamperTests.test_authoritative_and_projection_mutations", "StructuredTamperTests"],
    "journal_tamper": ["TamperTests.test_authoritative_and_projection_mutations"],
    "db_deletion_rebuild": ["MemoryTests.test_trust_search_supersession_trace_and_rebuild", "test_duplicate_keys_projection_lag_and_reads"],
    "crash_recovery": ["FaultTests.test_crash_matrix_valid_prefix_and_replay"],
    "windows_durability_characterization": ["FaultTests.test_windows_open_handle_rename_characterization"],
    "backup_restore": ["BackupTests"],
    "single_writer_fencing": ["test_single_writer_fencing_across_processes", "test_writer_crash_releases_os_lock", "test_native_database_refuses_accidental_independent_writer"],
    "actor_authorization": ["test_policy_authorization_is_actor_run_and_policy_bound", "test_spec_supersession_and_authorization_expiry_receipts"],
    "policy_engine": ["test_policy_authorization_is_actor_run_and_policy_bound", "ReleaseTests", "AuthorizationInterleavings"],
    "exposure_enforcement": ["test_terminal_open_is_guarded_and_retry_is_idempotent", "test_policy_changes_before_queued_protected_open", "test_new_truth_contact_invalidates_live_consumption"],
    "resource_leases": ["test_gpu_collision_expiry_and_stale_fence"],
    "stale_fencing_rejection": ["test_gpu_collision_expiry_and_stale_fence", "test_stale_lease_rejects_execution_and_return"],
    "adapter_registry": ["test_adapter_preserves_source_identity"],
    "failure_history_queries": ["LifecycleTests", "test_typed_history_uses_registered_evidence_and_rebuilds"],
    "contact_evidence_scope": ["test_history_api_keeps_imported_claims_scoped"],
    "remote_execution": ["test_signed_bundle_worker_return_and_tamper"],
    "remote_tamper_replay": ["RemoteAdversarialTests", "StructuredTamperTests"],
    "memory_plane": ["MemoryTests", "test_memory_write_search_during_custody_ingestion"],
    "fts_retrieval": ["test_trust_search_supersession_trace_and_rebuild"],
    "vector_retrieval": ["test_trust_search_supersession_trace_and_rebuild"],
    "graph_retrieval": ["test_trust_search_supersession_trace_and_rebuild"],
    "memory_custody_trace": ["test_trust_search_supersession_trace_and_rebuild"],
    "mcp_interface": ["ExternalClientTests", "MCPTests"], "python_sdk": ["ExternalClientTests"],
    "rust_sdk": ["ExternalClientTests"], "e4_legacy_reconstruction": [], "cleanroom_replay": [],
    "phoenix_vault": ["VaultTests.test_source_generation_reader_and_rebuild",
                      "VaultTests.test_large_asset_streams_past_json_limit",
                      "VaultTests.test_full_size_document_stream_and_replay",
                      "VaultTests.test_other_actor_cannot_open_vault",
                      "VaultTests.test_portable_vault_reopens_on_another_library_and_rejects_tamper"],
}
GATE_REPORTS = {
    "db_deletion_rebuild": ["cleanroom", "http_cleanroom", "custody"],
    "crash_recovery": ["http_cleanroom"], "backup_restore": ["cleanroom", "http_cleanroom"],
    "resource_leases": ["collision", "custody"], "stale_fencing_rejection": ["collision", "http_cleanroom"],
    "failure_history_queries": ["e4"], "contact_evidence_scope": ["e4"],
    "remote_execution": ["remote", "http_cleanroom"], "memory_plane": ["memory"],
    "fts_retrieval": ["memory"], "vector_retrieval": ["memory"], "graph_retrieval": ["memory"],
    "memory_custody_trace": ["memory", "http_cleanroom"], "rust_sdk": ["rust"],
    "e4_legacy_reconstruction": ["e4"], "cleanroom_replay": ["cleanroom", "http_cleanroom"],
}
