[package]
name = "phoenix-dynamic-ner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
jina-router = ["dep:phoenix-embed"]

[dependencies]
compact_str.workspace = true
daachorse.workspace = true
memchr.workspace = true
rustc-hash.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true

phoenix-alex = { path = "../phoenix-alex" }
phoenix-types = { path = "../phoenix-types" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
phoenix-embed = { path = "../phoenix-embed", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
phoenix-embed = { path = "../phoenix-embed" }
phoenix-rel-post = { path = "../phoenix-rel-post" }
serde_json.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "ner_bench"
harness = false
