[package]
name = "phoenix-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
arc-swap.workspace = true
phoenix-graph = { path = "../phoenix-graph" }
phoenix-graph-kernel = { path = "../phoenix-graph-kernel" }
serde.workspace = true
