[package]
name = "phoenix-scope-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
hashbrown.workspace = true
rustc-hash.workspace = true
serde.workspace = true
phoenix-semantic-v2 = { path = "../phoenix-semantic-v2" }
phoenix-store-native-core = { path = "../phoenix-store-native-core" }
phoenix-types = { path = "../phoenix-types" }
