[package]
name = "adaptive-runtime-ar-00c-int1"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
adaptive-runtime-ar-00 = { package = "adaptive-runtime-ar-00", path = "../ar-00" }
hashbrown = "0.16"

[[bench]]
name = "ar00c_int1"
harness = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
